#:schema node_modules/wrangler/config-schema.json
name = "dmarcrenderanalyticsdashboard"
main = "src/index.js"
compatibility_date = "2024-12-30"
compatibility_flags = ["nodejs_compat"]

# Workers Logs
# Docs: https://developers.cloudflare.com/workers/observability/logs/workers-logs/
# Configuration: https://developers.cloudflare.com/workers/observability/logs/workers-logs/#enable-workers-logs
[vars]
JWT_SECRET_KEY = "secret"

[observability]
enabled = true

[[d1_databases]]
binding = "DB"
database_name = "dmarc-reports"
database_id = "4eb8c158-eb83-4492-999c-d94106ba10cb"

[[kv_namespaces]]
binding = "HUZZANDBUZZ_ACCOUNTS"
id = "813ec6c73e6f4fbaad2f442a749a81b6"
